#!/usr/bin/env python3
"""Generate the Android starting-window cube from the intro's t=0 projection.

Run with uv run --no-project tools/launch-time/cube_drawable.py.
No bitmap, native library, font or game renderer is needed to display this asset.
"""
from math import cos, sin, radians, sqrt, tan
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
YAW, TILT = radians(-125), radians(-12)
CAMERA = (0, 2.6, 6.8)
TARGET = (0, .45, 0)
# Furthest shell corner is 93dp from the centre, inside Android's 96dp icon mask.
REFERENCE_HEIGHT_DP = 640
FOCAL = REFERENCE_HEIGHT_DP / (2 * tan(radians(20)))


def dot(a, b):
    return sum(x * y for x, y in zip(a, b))


def norm(v):
    return tuple(x / sqrt(dot(v, v)) for x in v)


def rotate(v):
    x, y, z = v
    x, y = x * cos(TILT) - y * sin(TILT), x * sin(TILT) + y * cos(TILT)
    return (x * cos(YAW) + z * sin(YAW), y, -x * sin(YAW) + z * cos(YAW))


forward = norm(tuple(t - c for t, c in zip(TARGET, CAMERA)))
up = (0, -forward[2], forward[1])


def project(v, size):
    v = rotate(v)
    relative = tuple(v[i] * size + TARGET[i] - CAMERA[i] for i in range(3))
    depth = dot(relative, forward)
    return (144 + relative[0] * FOCAL / depth, 144 - dot(relative, up) * FOCAL / depth)


# Visible faces of the actual opening pose; material lighting matches BoxMeshKit.
faces = [
    ((1, 0, 0), [( .5, -.5, -.5), ( .5, -.5, .5), ( .5, .5, .5), ( .5, .5, -.5)]),
    ((0, 1, 0), [(-.5, .5, -.5), ( .5, .5, -.5), ( .5, .5, .5), (-.5, .5, .5)]),
    ((0, 0, -1), [(-.5, -.5, -.5), ( .5, -.5, -.5), ( .5, .5, -.5), (-.5, .5, -.5)]),
]
lights = [(norm((.45, .85, .35)), (.85, .85, .8)), (norm((-.6, .2, -.5)), (.25, .22, .3))]


def face_color(normal, base):
    n = rotate(normal)
    rgb = [min(1, base[i] * (ambient + sum(max(0, dot(n, direction)) * color[i]
           for direction, color in lights))) for i, ambient in enumerate((.55, .55, .6))]
    return '#' + ''.join(f'{round(c * 255):02X}' for c in rgb)


paths = []
for size, alpha, base in [(.9 * .82, 1, (1, .55, .78)), (.9 * 1.18 * .82, .22, (1, .595, .802))]:
    for normal, points in faces:
        coords = [project(v, size) for v in points]
        data = 'M' + ' L'.join(f'{x:.3f},{y:.3f}' for x, y in coords) + ' Z'
        paths.append(f'    <path android:fillColor="{face_color(normal, base)}" '
                     f'android:fillAlpha="{alpha}" android:pathData="{data}"/>')

output = '''<?xml version="1.0" encoding="utf-8"?>
<!-- Generated by tools/launch-time/cube_drawable.py; same pose as CubeOpening. -->
<vector xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:tools="http://schemas.android.com/tools" tools:ignore="VectorRaster"
    android:width="288dp" android:height="288dp"
    android:viewportWidth="288" android:viewportHeight="288">
''' + '\n'.join(paths) + '\n</vector>\n'
(ROOT / 'app/src/main/res/drawable/launch_cube.xml').write_text(output)
