// Generated by tools/launch-time/motion_assets.py.
package cube.run.intro

import cube.run.R

internal object LaunchThemes {
    val skins = intArrayOf(R.style.LaunchSkin0, R.style.LaunchSkin1, R.style.LaunchSkin2, R.style.LaunchSkin3, R.style.LaunchSkin4, R.style.LaunchSkin5, R.style.LaunchSkin6, R.style.LaunchSkin7, R.style.LaunchSkin8, R.style.LaunchSkin9, R.style.LaunchSkin10, R.style.LaunchSkin11, R.style.LaunchSkin12, R.style.LaunchSkin13, R.style.LaunchSkin14, R.style.LaunchSkin15, R.style.LaunchSkin16, R.style.LaunchSkin17, R.style.LaunchSkin18, R.style.LaunchSkin19, R.style.LaunchSkin20, R.style.LaunchSkin21, R.style.LaunchSkin22, R.style.LaunchSkin23)
    val worlds = intArrayOf(R.style.LaunchWorld1, R.style.LaunchWorld2, R.style.LaunchWorld3, R.style.LaunchWorld4, R.style.LaunchWorld5)
}
